/**
 * Created by anchao on 2016/6/29.
 */
export const SHOWDIALOG_COMMON = 'SHOWDIALOG_COMMON'
export const HIDEDIALOG_COMMON = 'HIDEDIALOG_COMMON'
export const SETFOOTER_COMMON = 'SETFOOTER_COMMON'
